apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-config
  namespace: hallphotography
data:
  resolv.conf: |
    nameserver 10.43.0.10
    nameserver 8.8.8.8
    nameserver 1.1.1.1
    search hallphotography.svc.cluster.local svc.cluster.local cluster.local
    options ndots:5
